### ISSUE TITLE
`TF_regression` not working properly on server (or locally either)

### ISSUE THREAD

**Issue by iamjli** [fraenkel-lab/GarNet#39]
```fc-list: error while loading shared libraries: libexpat.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/nfs/latdata/iamjli/packages/GarNet2/venv/lib/python3.6/site-packages/pandas/indexes/base.py", line 2134, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
KeyError: 'expression'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/latdata/iamjli/packages/GarNet2/venv/lib/python3.6/site-packages/pandas/tools/plotting.py", line 3774, in __call__
    sort_columns=sort_columns, **kwds)
  File "/nfs/latdata/iamjli/packages/GarNet2/venv/lib/python3.6/site-packages/pandas/tools/plotting.py", line 2643, in plot_frame
    **kwds)
  File "/nfs/latdata/iamjli/packages/GarNet2/venv/lib/python3.6/site-packages/pandas/tools/plotting.py", line 2470, in _plot
    plot_obj.generate()
  File "/nfs/latdata/iamjli/packages/GarNet2/venv/lib/python3.6/site-packages/pandas/tools/plotting.py", line 1043, in generate
    self._make_plot()
  File "/nfs/latdata/iamjli/packages/GarNet2/venv/lib/python3.6/site-packages/pandas/tools/plotting.py", line 1619, in _make_plot
    scatter = ax.scatter(data[x].values, data[y].values, c=c_values,
  File "/nfs/latdata/iamjli/packages/GarNet2/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 2059, in __getitem__
    return self._getitem_column(key)
  File "/nfs/latdata/iamjli/packages/GarNet2/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)
  File "/nfs/latdata/iamjli/packages/GarNet2/venv/lib/python3.6/site-packages/pandas/core/generic.py", line 1386, in _get_item_cache
    values = self._data.get(item)
  File "/nfs/latdata/iamjli/packages/GarNet2/venv/lib/python3.6/site-packages/pandas/core/internals.py", line 3543, in get
    loc = self.items.get_loc(item)
  File "/nfs/latdata/iamjli/packages/GarNet2/venv/lib/python3.6/site-packages/pandas/indexes/base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
KeyError: 'expression'```

**Comment by iamjli** [comment]
figured it out, expression file contained some impurities. Added a few lines to parsing function to filter things like this out. https://github.com/fraenkel-lab/GarNet/commit/b451113635f787789f4fe98e9647766d843180f7

**Comment by zfrenchee** [comment]
@iamjli Nice!
