### ISSUE TITLE
GarNet File has inconsistent naming convention for record:

### ISSUE THREAD

**Issue by zfrenchee** [fraenkel-lab/GarNet#44]
@iamjli I was testing GarNet when I ran into a bug. I was following the notebook, and I created a GarNet file and then tried to map peaks using that GarNet file. I got this error:

```
***** WARNING: File  has inconsistent naming convention for record:
	motifChrom	motifStart	motifEnd	motifName	motifScore	motifStrand	geneName	tssStart	tssEnd	motif_gene_distance

***** WARNING: File  has inconsistent naming convention for record:
	motifChrom	motifStart	motifEnd	motifName	motifScore	motifStrand	geneName	tssStart	tssEnd	motif_gene_distance
```

and an empty dataframe. However, when I used `garnetDB_cisBP.hg19.LOD.10kb.tsv` instead of `garnetDB_cisBP.hg19.LOD.10kb.chr1_SLIM.tsv` the error disappeared. 

This might point to an issue with `construct_garnet_file`. Let me know what you think.

**Comment by iamjli** [comment]
It may be that there are no matching peaks for the slim file, and the dataframe should in fact be empty. If so, we could easily add a catch line. Would be easier to diagnose this in person tho.

**Comment by iamjli** [comment]
I ran into this error as well, and it's not what I thought previously. There is indeed overlap between peaks and motifs. 

It runs with no errors when I use a python instance on the server. I tried testing it on a python instance on my local machine, but I'm getting this new error when I try to import Garnet, and I don't know how to fix it. 

```
Python 3.6.1 (default, Jun  7 2017, 14:30:26)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append("../GarNet")
>>> import garnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../GarNet/garnet.py", line 16, in <module>
    import matplotlib.pyplot as plt
  File "/Users/jonathanli/Documents/research/packages/GarNet2/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/jonathanli/Documents/research/packages/GarNet2/venv/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/jonathanli/Documents/research/packages/GarNet2/venv/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/Users/jonathanli/Documents/research/packages/GarNet2/venv/lib/python3.6/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/Users/jonathanli/Documents/research/packages/GarNet2/venv/lib/python3.6/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/Users/jonathanli/Documents/research/packages/GarNet2/venv/lib/python3.6/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by iamjli** [comment]
I started checking old commits, and I can't reproduce the error anymore, works fine. Even when I come to the most recent commit, notebook works fine. I'm still getting the _tkinter error above tho when i run in python instance.

**Comment by AmandaKedaigle** [comment]
TKinter is also related to the errors Natasha and I were getting when running on the cluster (Don't remember if the error was exactly the same)

**Comment by zfrenchee** [comment]
@iamjli This error disappeared for me as well. 

@AmandaKedaigle let's open a fresh issue for the TKinter error
